# separator text
full_text=

command=~/.i3/i3blocks/$BLOCK_NAME	
align=center
color=#cccccc
separator=false
separator_block_width=15

[capslock]
full_text=
short_text=
separator=true
interval=once
color=#ffffff
signal=11

[numlock]
full_text=
short_text=
separator=false
interval=once
color=#ffffff
signal=11

[separator]

[cpu_label]
full_text=
separator=false
color=#99cc99

[cpu_temp]
interval=10

[separator]

[eth_label]
full_text=
separator=false
color=#6699cc

[eth]
interval=10

[separator]

[wlan_label]
full_text=
separator=false
color=#6699cc

[wlan]
interval=10

[separator]

[battery_label]
interval=10
separator=false
color=#6699cc

[battery]
interval=10
color=#99cc99

[battery_ext_label]
interval=10
separator=false
color=#6699cc

[battery_ext]
interval=10
color=#99cc99

[separator]

[date_text]
full_text=
color=#b777e0

[date]
command=date '+%d/%m/%Y'
interval=360
separator=false

[separator]

[time_text]
full_text=
color=#b777e0

[time]
command=date '+%H:%M:%S'
interval=1
separator=false

[separator]
