# separator text
full_text=

command=~/.i3/i3blocks/$BLOCK_NAME	
align=center
color=#FAFAFA
separator=false
separator_block_width=15

[capslock]
full_text=
short_text=
separator=true
interval=once
color=#ffffff
signal=11

[numlock]
full_text=
short_text=
separator=false
interval=once
color=#ffffff
signal=11

[separator]

[cpu_label]
full_text=
separator=false
color=#73D216

[cpu_temp]
interval=10

[separator]

[eth_label]
full_text=
separator=false
color=#66D9EF

[eth]
interval=10

[separator]

[wlan_label]
full_text=
separator=false
color=#66D9EF

[wlan]
interval=10

[separator]

[battery_label]
interval=10
separator=false
color=#66D9EF

[battery]
interval=10
color=#73D216

[separator]

[date_text]
full_text=
color=#abc2ab

[date]
command=date '+%d/%m/%Y'
interval=360
separator=false

[separator]

[time_text]
full_text=
color=#abc2ab

[time]
command=date '+%H:%M:%S'
interval=1
separator=false

[separator]
