[gmail]
server = "imap.gmail.com"
port = 993
username = "j.reedts@gmail.com"
pwcmd = "pass email/gmail/buzz"
notificationcmd = "mail_refresh private/gmail"

[wwu]
server = "imap.uni-muenster.de"
port = 993
username = "j_bigg01"
pwcmd = "pass uni/mail/julian.bigge"
notificationcmd = "mail_refresh private/wwu"
