# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$singularity\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$fill\
[](bg:#474b51 fg:#383a3e)\
$package\
$c\
$cmake\
$conda\
$python\
$rust\
$time\
$cmd_duration\
$status
$character"""

# Inserts a blank line between shell prompts
add_newline = false

[c]
detect_extensions = ["c", "cpp", "cxx", "h", "hpp", "hxx"]
symbol = " "
style = "bg:#383a3e fg:cyan"
format = "[]($style)[ $symbol($version(-$name)) ](bold $style)"

[character]
vimcmd_symbol = "[](bold green)"

[cmake]
symbol = " "
style = "bg:#383a3e fg:blue"
format = "[]($style)[ $symbol($version) ](bold $style)"

[cmd_duration]
style = "fg:#474b51 bg:yellow"
format = "[\\[~ $duration\\]](bold $style)"

[conda]
style = "bg:#383a3e fg:green"
ignore_base = false
format = "[]($style)[ $symbol$environment ](bold $style)"

[directory]
style = "bg:#5f875f fg:#d7ffaf"
read_only_style = "bg:red fg:black"
repo_root_style = "bg:blue fg:bold black"
repo_root_format = "[$before_root_path](bg:blue fg:black)[$repo_root]($repo_root_style)[$path ](bg:blue fg:black)([ $read_only ]($read_only_style))[](fg:blue bg:purple)"
format = "[$path ]($style)([ $read_only ]($read_only_style))[](fg:#5f875f bg:#474b51)"
truncation_symbol = "…/"
truncate_to_repo = false

[fill]
symbol = " "
style = "bg:#474b51"

[git_branch]
style = "fg:#474b51 bg:purple"
format = "[ $symbol$branch(:$remote_branch) ](bold $style)[](fg:purple bg:#474b51)"
symbol = " "

[git_status]
style = "bg:#474b51 fg:bold red"
format = "([\\[$all_status$ahead_behind\\]]($style))"

[hostname]
ssh_only = true
ssh_symbol = " "
style = "green"

[username]
style_user = "bold green"
format = "[$user]($style)@"

[package]
style = "bg:#383a3e fg:208"
symbol = " "
format = "[]($style)[ $symbol$version ](bold $style)"

[python]
style = "bg:#383a3e fg:yellow"
symbol = " "
format = "[]($style)[ ${symbol}${pyenv_prefix}(${version} )(\\($virtualenv\\))](bold $style)"

[rust]
style = "bg:#383a3e fg:red"
symbol = " "
format = "[]($style)[ $symbol($version) ](bold $style)"

[status]
disabled = false
pipestatus = true
map_symbol = true
sigint_symbol = ""
signal_symbol = "ﲍ"
not_found_symbol = ""
pipestatus_separator = "[|]($style)"
style = "bg:red bold fg:black"
format = "[](bg:yellow fg:red)[$symbol ($common_meaning )($signal_name )($maybe_int)]($style)"
pipestatus_format = "[](bg:#474b51 fg:red)[$pipestatus  $symbol $common_meaning $signal_name $maybe_int]($style)"
pipestatus_segment_format = "[$symbol$common_meaning$signal_name $maybe_int]($style)"

[time]
style = "fg:#474b51 bg:yellow"
disabled = false
format = "[](bg:#383a3e fg:yellow)[  $time ]($style)"
