# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$singularity\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$package\
$c\
$cmake\
$conda\
$python\
$rust\
$fill
$time\
$character\
"""

right_format = """
$cmd_duration\
$status\
"""

# Inserts a blank line between shell prompts
add_newline = false

[c]
detect_extensions = ["c", "cpp", "cxx", "h", "hpp", "hxx"]
symbol = " "
style = "bg:#383a3e fg:cyan"
format = "[](bg:18 fg:242)[ $symbol($version(-$name)) ](bold $style)"

[character]
success_symbol = "[/](bold green)"
error_symbol = '[\\](bold red)'
vimcmd_symbol = "[-](yellow)[](bold yellow)"

[cmake]
symbol = "󰇂 "
style = "bg:18 fg:blue"
format = "[](bg:18 fg:242)[ $symbol($version) ](bold $style)"

[cmd_duration]
style = "bold yellow"
format = "[\\[~ $duration\\]]($style) "

[conda]
style = "bg:18 bold green"
ignore_base = false
format = "[](bg:18 fg:242)[ $symbol$environment ]($style)"

[directory]
style = "bg:18 bold blue"
read_only_style = "bg:18 fg:red"
repo_root_style = "bg:18 bold cyan"
repo_root_format = "[ $before_root_path]($style)[$repo_root]($repo_root_style)[$path]($style)([ $read_only ]($read_only_style))"
format = "[ $path]($style)([ $read_only ]($read_only_style))"
truncation_symbol = "⋯/"
read_only = " "
truncate_to_repo = false

[fill]
symbol = " "
style = "bg:18"

[git_branch]
style = "bg:18 bold purple"
format = "[ $symbol$branch(:$remote_branch) ](bold $style)"
symbol = " "

[git_status]
style = "bg:18 bold red"
format = "([\\[$all_status$ahead_behind\\] ]($style))"

[hostname]
ssh_only = true
ssh_symbol = " "
style = "purple bg:18"
format = "[$hostname $ssh_symbol]($style)"

[username]
show_always = true
style_user = "bg:18 green"
style_root = "bg:18 bold red"
format = "[$user]($style)[@](bg:18 cyan)"

[package]
style = "bg:18 bold 208"
symbol = " "
format = "[](bg:18 fg:242)[ $symbol$version ]($style)"

[python]
style = "bg:18 bold yellow"
symbol = " "
format = "[](bg:18 fg:242)[ ${symbol}${pyenv_prefix}(${version})(\\($virtualenv\\)) ]($style)"

[rust]
style = "bg:18 bold red"
symbol = " "
format = "[](bg:18 fg:242)[ $symbol($version) ](bold $style)"

[status]
disabled = false
pipestatus = true
map_symbol = true
symbol = " "
not_executable_symbol = " "
sigint_symbol = ""
signal_symbol = "󰌬 "
not_found_symbol = "󰍉 "
pipestatus_separator = "[│]($style)"
style = "bold red"
format = "[$symbol ($common_meaning )($signal_name )($maybe_int)]($style)"
pipestatus_format = "[$pipestatus  $symbol$common_meaning$signal_name$maybe_int]($style)"

[time]
style = "242"
disabled = false
format = "[\\(](246)[$time]($style)[\\)](246) "
