#!/bin/sh

STATUS=$( acpi -b | cut -d , -f 2-3 | sed s/,//g | awk '{print $1 " " ($2)}' | cut -d : -f 1-2 )
PERCENT=${STATUS%\%*}

if [ $PERCENT -ge 90 ]; then
	printf " "
elif [ $PERCENT -ge 75 ]; then
	printf " "
elif [ $PERCENT -ge 50 ]; then
	printf " "
elif [ $PERCENT -ge 25 ]; then
	printf " "
else
	printf "%s  %s" "" "$STATUS"
	exit 33
fi

printf " %s" "$STATUS"
exit 0

